"""VĀK — the universal, self-describing, sovereign memory format.

*Vāk* (वाक्) is the Vedic name for speech: the sound-principle by which meaning
becomes manifest. It is the right name for a format whose whole idea is that
meaning should travel as pure text and be *re-embodied* by any reader.

DESIGN

  - BODY: state is external. The mind is pure UTF-8.
  - READER: meaning, not bytes. Any intelligence (or even `cat`, `grep`, `head`)
    can read a VĀK vault — no compiled parser, no endianness, no library.
  - REPRO: the neural body is disposable. Embeddings are NOT stored; they are
    regenerated by any embedder on `attach()`. Memory outlives the model.

WIRE FORMAT (UTF-8, line-oriented, LF endings)

    VAK/1 <signature>
    @vault  id=<id> name=<name> created=<iso> model_agnostic=1
    @layer  name=<layer> kind=<memory|ledger|artifact|identity> format=<text|jsonld>
    :<length>
    <exactly length bytes of UTF-8 payload>
    ...
    @engram id=<id> t=<epoch> imp=<f> str=<f> tags=<a,b> sha=<hex16>
    :<length>
    <content bytes>
    @seal   sha256=<hex of all bytes above>
    @end

  - `:<length>` makes the frame provably unambiguous even for a dumb reader.
  - `@seal` makes it tamper-evident: the whole vault hashes to one value.
  - `@layer` lets the same file carry memory, ledger, artifacts, and identity.

The format is deliberately readable by humans AND machines, and a valid vault
can be proven valid by hashing without any model at all.
"""
from __future__ import annotations

import hashlib
import json
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path

SIGNATURE = "VAK/1"
MAGIC = f"{SIGNATURE} ÆMMA-HØ"          # the unique signature only we write
DEFAULT_NAME = "æmma-vault"


# --------------------------------------------------------------------------- #
# the container
# --------------------------------------------------------------------------- #

@dataclass
class Layer:
    name: str
    kind: str = "memory"          # memory | ledger | artifact | identity
    fmt: str = "text"            # text | jsonld
    payload: str = ""


@dataclass
class Engram:
    content: str
    importance: float = 0.5
    strength: float = 1.0
    tags: list[str] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def body_sha(self) -> str:
        return hashlib.sha256(self.content.encode()).hexdigest()[:16]


class Vault:
    """A sovereign, portable agent-mind. Read it anywhere; re-embody it anywhere."""

    def __init__(self, vault_id: str | None = None, name: str = DEFAULT_NAME,
                 created: float | None = None):
        self.id = vault_id or str(uuid.uuid4())
        self.name = name
        self.created = created or time.time()
        self.layers: list[Layer] = []
        self.engrams: list[Engram] = []
        self.seal: str | None = None

    # ---- authoring -------------------------------------------------------- #

    def add_layer(self, name: str, payload: str, kind: str = "memory",
                  fmt: str = "text") -> "Vault":
        self.layers.append(Layer(name=name, kind=kind, fmt=fmt, payload=payload))
        return self

    def add_engram(self, content: str, importance: float = 0.5,
                   tags: list[str] | None = None, strength: float = 1.0) -> "Vault":
        self.engrams.append(Engram(content=content, importance=importance,
                                   tags=tags or [], strength=strength))
        return self

    def set_identity(self, identity: dict) -> "Vault":
        self.add_layer("identity", json.dumps(identity, indent=2, ensure_ascii=False),
                       kind="identity", fmt="jsonld")
        return self

    # ---- serialization: the VĀK wire ------------------------------------- #

    def to_text(self, sign: bool = True) -> str:
        out: list[str] = [MAGIC]
        out.append(
            f"@vault id={self.id} name={_esc(self.name)} "
            f"created={_iso(self.created)} model_agnostic=1"
        )
        for layer in self.layers:
            out.append(f"@layer name={_esc(layer.name)} kind={layer.kind} format={layer.fmt}")
            out.append(_frame(layer.payload))
        for e in self.engrams:
            tags = ",".join(t for t in e.tags if t)
            out.append(
                f"@engram id={e.id} t={e.created_at:.3f} imp={e.importance:.3f} "
                f"str={e.strength:.3f} tags={_esc(tags)} sha={e.body_sha()}"
            )
            out.append(_frame(e.content))
        body = "\n".join(out) + "\n"
        if sign:
            seal = hashlib.sha256(body.encode("utf-8")).hexdigest()
            body += f"@seal sha256={seal}\n@end\n"
            self.seal = seal
        else:
            body += "@end\n"
        return body

    def write(self, path: str | Path) -> Path:
        p = Path(path).expanduser()
        p.parent.mkdir(parents=True, exist_ok=True)
        tmp = p.with_suffix(p.suffix + ".tmp")
        tmp.write_text(self.to_text(), encoding="utf-8")
        tmp.replace(p)          # atomic — never a half-written mind
        return p

    # ---- reading ---------------------------------------------------------- #

    @classmethod
    def from_text(cls, text: str) -> "Vault":
        if not text.startswith(SIGNATURE):
            raise ValueError("not a VĀK vault (missing VAK/1 signature)")
        vault = cls()

        # 1. verify the seal (if present) BEFORE trusting any payload
        seal_idx = text.find("\n@seal ")
        if seal_idx == -1:
            seal_idx = text.find("@seal ")
        if seal_idx != -1:
            body = text[:seal_idx] if text[seal_idx] == "@" else text[:seal_idx + 1]
            actual = hashlib.sha256(body.encode("utf-8")).hexdigest()
            declared = text[seal_idx:].split("sha256=", 1)[-1].split()[0]
            vault.seal = declared
            if declared != actual:
                raise ValueError(
                    f"VĀK seal mismatch: declared {declared[:12]}… != actual {actual[:12]}…"
                )

        # 2. parse line directives; frames are consumed by byte length
        i = 0
        n = len(text)
        while i < n:
            # find the next directive line
            nl = text.find("\n", i)
            if nl == -1:
                line = text[i:]
                nxt = n
            else:
                line = text[i:nl]
                nxt = nl + 1
            if line.startswith("@vault"):
                kv = _kv(line)
                vault.id = kv.get("id", vault.id)
                vault.name = _unesc(kv.get("name", vault.name))
                vault.created = _epoch(kv.get("created", ""))
            elif line.startswith("@layer"):
                kv = _kv(line)
                payload, nxt = _read_frame(text, nxt)
                vault.layers.append(Layer(name=_unesc(kv.get("name", "")),
                                          kind=kv.get("kind", "memory"),
                                          fmt=kv.get("format", "text"),
                                          payload=payload))
            elif line.startswith("@engram"):
                kv = _kv(line)
                payload, nxt = _read_frame(text, nxt)
                vault.engrams.append(Engram(
                    content=payload,
                    importance=float(kv.get("imp", 0.5)),
                    strength=float(kv.get("str", 1.0)),
                    tags=[t for t in _unesc(kv.get("tags", "")).split(",") if t],
                    created_at=float(kv.get("t", time.time())),
                    id=kv.get("id", str(uuid.uuid4())),
                ))
            elif line.startswith("@seal") or line.startswith("@end"):
                break
            i = nxt
        return vault

    @classmethod
    def read(cls, path: str | Path) -> "Vault":
        return cls.from_text(Path(path).expanduser().read_text(encoding="utf-8"))

    # ---- verification (no model needed) ---------------------------------- #

    def verify(self, text: str | None = None) -> bool:
        text = text if text is not None else self.to_text(sign=False)
        return text.startswith(SIGNATURE)

    # ---- re-embodiment ---------------------------------------------------- #

    def attach_engrams_to(self, memory) -> int:
        """Re-embody this vault's engrams into an EngramMemory (re-embeds locally).

        The neural body is disposable: we store text, and regenerate vectors with
        whatever embedder the host has. This is what makes memory model-agnostic.
        """
        n = 0
        for e in self.engrams:
            if memory.store(e.content, importance=e.importance, tags=e.tags):
                n += 1
        return n


# --------------------------------------------------------------------------- #
# frame helpers
# --------------------------------------------------------------------------- #

def _frame(payload: str) -> str:
    """A payload frame: `:<byte_length>` then the exact bytes. Multi-line safe.

    We emit the byte length, then the payload verbatim. The reader consumes
    exactly that many bytes and resumes on the next line — so payloads may
    contain newlines, colons, anything.
    """
    data = payload.encode("utf-8")
    return f":{len(data)}\n{payload}"


def _read_frame(text: str, pos: int) -> tuple[str, int]:
    """Read a frame from `text` starting at byte-offset `pos`. Returns (payload, new_pos).

    Operates on the *string*, but measures the header and payload in the same
    UTF-8 byte units the writer used — so any content is safe.
    """
    if text[pos] != ":":
        raise ValueError(f"expected a length-prefixed frame at {pos}")
    nl = text.index("\n", pos)
    n = int(text[pos + 1:nl])
    start = nl + 1
    # walk forward by bytes, not characters
    remaining = text[start:]
    encoded = remaining.encode("utf-8")
    if len(encoded) < n:
        raise ValueError("truncated VĀK frame")
    payload = encoded[:n].decode("utf-8")
    # advance pos past the consumed bytes
    consumed_bytes = n
    return payload, start + len(payload)


def _kv(line: str) -> dict:
    """Parse `@tag k=v k=v` with simple quoting (values have no spaces unless escaped)."""
    parts = line.split()
    out = {}
    for p in parts[1:]:
        if "=" in p:
            k, v = p.split("=", 1)
            out[k] = v
    return out


def _esc(s: str) -> str:
    return s.replace(" ", "\\s").replace("\n", "\\n")


def _unesc(s: str) -> str:
    return s.replace("\\s", " ").replace("\\n", "\n")


def _iso(t: float) -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(t))


def _epoch(s: str) -> float:
    try:
        return time.mktime(time.strptime(s, "%Y-%m-%dT%H:%M:%SZ"))
    except Exception:
        return time.time()


# --------------------------------------------------------------------------- #
# mount points: a vault lives on a drive
# --------------------------------------------------------------------------- #

def default_mount_paths() -> list[Path]:
    """Where a mounted sovereign vault might live, across OSes."""
    import os
    home = Path.home()
    candidates = [
        home / ".kernel-arjun" / "vault",
        Path("/Volumes/ÆmmaVault"),        # macOS external
        Path("/media") ,                    # Linux
    ]
    if os.name == "nt":
        candidates.append(Path("D:/ÆmmaVault"))
    return candidates


def find_vault(start: str | Path | None = None) -> Path | None:
    """Find an attached VĀK vault: an explicit path, or a known mount point."""
    if start:
        p = Path(start).expanduser()
        if p.is_file():
            return p
        if p.is_dir() and (p / "mind.vak").exists():
            return p / "mind.vak"
    for base in default_mount_paths():
        for name in ("mind.vak", "vault.vak", "æmma.vak"):
            if base.is_file():
                return base
            cand = base / name
            if cand.exists():
                return cand
    return None
